name: Docker Image CI

on:
  push:
    branches: [ ghActions ]
  pull_request:
    branches: [ ghActions ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # - name: Build the Docker image
    #   working-directory: ./ansible270
    #   run: docker build -t danielnbalasoiu/docker-ansible:3.15-2.7.0 -f ./Dockerfile .

    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: danielnbalasoiu/docker-ansible
        tags: 2.7.0, 3.15-2.7.0
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        directory: ./ansible270
