name: Build and Publish

on:
  push:
    # run it on push to the default repository branch
    branches: [ ghActions ]
  # run it during pull request
  pull_request:
    branches: [ ghActions ]

jobs:
  # define job to build and publish docker image
  build-and-push-docker-image:
    name: Build Docker image and push to repositories
    # run only when code is compiling and tests are passing
    runs-on: ubuntu-latest

    # steps to perform in job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # setup Docker buld action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub Container Registry
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: ./ansible270
          # Note: tags has to be all lower-case
          tags: |
            danielnbalasoiu/docker-ansible:${{ github.sha }}
            danielnbalasoiu/docker-ansible:3.15-2.7.0
            danielnbalasoiu/docker-ansible:2.7.0
          # build on feature branches, push only on ghActions branch
          push: ${{ github.ref == 'refs/heads/ghActions' }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'docker.io/danielnbalasoiu/docker-ansible:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
